// <auto-generated />
using System;
using FoodDonationMicroservice.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodDonationMicroservice.Migrations
{
    [DbContext(typeof(FoodDonationContext))]
    [Migration("20210907152034_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodDonationMicroservice.Models.FoodDonations", b =>
                {
                    b.Property<string>("DonationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodEntryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonationId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            DonationId = "1",
                            CollectionId = "234t6d3",
                            CreatedBy = "asd2sda",
                            CreatedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(2163),
                            DonationName = "Raffles Hotel Lunch Buffet",
                            FoodEntryId = "1120",
                            ReservedBy = "FoodForSg",
                            ReservedDate = new DateTime(2021, 9, 7, 23, 20, 34, 453, DateTimeKind.Local).AddTicks(4191),
                            UpdatedBy = "asd2sda",
                            UpdatedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(2642),
                            UserId = "asd2sda"
                        },
                        new
                        {
                            DonationId = "2",
                            CollectionId = "s12dsaf",
                            CreatedBy = "kdsjfw2",
                            CreatedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(3077),
                            DonationName = "Marina Bay Sands Lunch Buffet",
                            FoodEntryId = "1240",
                            ReservedBy = "FoodFromTheHeart",
                            ReservedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(3073),
                            UpdatedBy = "kdsjfw2",
                            UpdatedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(3078),
                            UserId = "kdsjfw2"
                        },
                        new
                        {
                            DonationId = "3",
                            CollectionId = "jjksnf2",
                            CreatedBy = "kibjdf2",
                            CreatedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(3081),
                            DonationName = "Marina Bay Sands Lunch Buffet",
                            FoodEntryId = "1240",
                            ReservedBy = "SGFoodRescure",
                            ReservedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(3080),
                            UpdatedBy = "kibjdf2",
                            UpdatedDate = new DateTime(2021, 9, 7, 23, 20, 34, 454, DateTimeKind.Local).AddTicks(3082),
                            UserId = "kibjdf2"
                        });
                });

            modelBuilder.Entity("FoodDonationMicroservice.Models.FoodDescription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodDescriptions");
                });

            modelBuilder.Entity("FoodDonationMicroservice.Models.FoodEntry", b =>
                {
                    b.Property<string>("FoodEntryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FoodEntryId");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
